</> SQL
-- =====================================================
-- DATABASE : CRM SYSTEM
-- =====================================================
  
CREATE DATABASE IF NOT EXISTS CRM_SYSTEM;
USE CRM_SYSTEM;

-- =====================================================
-- TABLE: CUSTOMERS
-- =====================================================

CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(100),
EMAIL VARCHAR(100),
PHONE VARCHAR(20),
CITY VARCHAR(50)
);

-- =====================================================
-- TABLE: PRODUCTS
-- =====================================================

CREATE TABLE PRODUCTS (
PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(100),
PRICE DECIMAL(10,2)
);

-- =====================================================
-- TABLE: PRODUCTS
-- =====================================================

CREATE TABLE ORDERS (
ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_ID INT,
PRODUCT_ID INT,
ORDER_DATE DATE,
QUANTITY INT,

  -- FOREIGN KEYS
  FOREIGN KEY(CUSTOMER_ID)
  REFERENCES CUSTOMERS(CUSTOMER_ID),
  
  FOREIGN KEY(PRODUCT_ID)
  REFERENCES PRODUCTS(PRODUCT_ID)
);

-- =====================================================
-- SAMPLE DATA: CUSTOMERS
-- =====================================================

INSERT INTO CUSTOMERS (CUSTOMERNAME,EMAIL,PHONE,CITY) VALUES
('JOHN DOE','JOHN@EXAMPLE.COM',0987654321,'NEW YORK'),
('JANE SMITH','JONE@EXAMPLE.COM',1234567890,'LOS ANGELES'),
('ALICE JOHNSON','ALICE@EXAMPLE.COM',6789054321,'CHICAGO'),
('BOB BROWN','BOB@EXAMPLE.COM',6754893201,'HOUSTON'),
('JOHN BRITTO','JOHN@EXAMPLE.COM',6543278901,'LONDON'),
('WILLIAM RAI','WILLIAM@EXAMPLE.COM',7658904321,'AMERICA'),
('RIO RAI','RIO@EXAMPLE.COM',9087675436,'JERMAN');

-- =====================================================
-- SAMPLE DATA: PRODUCTS
-- =====================================================

INSERT INTO PRODUCTS (PRODUCTNAME,PRICE) VALUES
('LAPTON',1200.00),
('SMARTPHONE',800.00),
('TABLET',300.00),
('HEADPHONES',150.00),
('CHARGER HEAD',250.00),
('POWER CABLE',300.00),
('MOUSE',1500.00);

-- =====================================================
-- SAMPLE DATA: ORDERS
-- =====================================================

INSERT INTO ORDERS (CUSTOMER_ID,PRODUCTID,ORDER_DATE,QUANTITY) VALUES
(1,1,'2025-04-01',2),
(2,2,'2025-04-05',1),
(3,3,'2025-04-12',3),
(4,4,'2025-04-20',1),
(5,5,'2025-04-24',10),
(6,6,'2025-05-05',20),
(7,7,'2025-05-15',15);

-- =====================================================
-- QUERIES
-- =====================================================

ALTER TABLE CUSTOMERS ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE CUSTOMERS SET PHONE = '9999999999'
WHERE CUSTOMERNAME = 'JOHN DOE';

SELECT * FROM CUSTOMERS
WHERE CITY LIKE 'NEW%';

SELECT CUSTOMERNAME AS CUSTOMERNAME,CITY AS CUSTOMERCITY
FROM CUSTOMERS;

SELECT 
CUSTOMER_ID ,
COUNT(ORDER_ID)AS TOTAL_ORDERS,
SUM(QUANTITY)AS TOTAL_QUANTITY,
AVG(QUANTITY)AS AVG_QUANTITY
FROM ORDERS
GROUP BY CUSTOMER_ID
HAVING TOTAL_ORDERS>0;

SELECT * FROM CUSTOMERS
ORDER BY CUSTOMERNAME ASC
LIMIT 5;

SELECT 
O.ORDER_ID,
C.CUSTOMERNAME AS CUSTOMER_NAME,
P.PRODUCTNAME,
O.QUANTITY,
O.ORDER_DATE
FROM ORDERS O 
INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
INNER JOIN PRODUCTS P ON O.PRODUCTID = P.PRODUCTID
ORDER BY O.ORDER_DATE;

SELECT CUSTOMERNAME AS NAME 
FROM CUSTOMERS
UNION 
SELECT PRODUCTNAME 
FROM PRODUCTS;

SELECT CUSTOMERNAME AS NAME 
FROM CUSTOMERS
UNION ALL
SELECT PRODUCTNAME 
FROM PRODUCTS;

SELECT * FROM CUSTOMERS
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID
FROM ORDERS
WHERE QUANTITY>2);

SELECT * FROM PRODUCTS
WHERE PRODUCTID = (SELECT PRODUCTID
FROM ORDERS
ORDER BY QUANTITY DESC
LIMIT 1);


